name: Actionlint

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: actionlint-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
        with:
          reporter: github-check
          filter_mode: nofilter
          fail_level: error
